### ISSUE TITLE
Unable to deal with 'unusual' field names

### ISSUE THREAD

**Issue by dereksz** [cargomoose/ggraptR#14]
I happened to have a data.table where the columns were predominantly prefixed with a number, such as 
`1.Main.Station`.  I've gotten used to quoting these in back-ticks when I use them in ggplot and data.table functions, but raptR didn't fare as well, and errors on these column names.  I think this warrants being an issue, although admittedly a low priority one (I can simply rename my columns with an alpha prefix).

```
Listening on http://127.0.0.1:3024
Warning: Error in parse: <text>:1:3: unexpected symbol
1: 1.Main.Station
      ^
Stack trace (innermost first):
    118: parse
    117: FUN
    116: lapply
    115: aes_string
    114: inherits
    113: ggplot.data.frame
    112: ggplot
    111: get_ggplot [functions/ggraptplot.R#2]
    110: plotScatter [./functions/plot.R#36]
    109: reactive scatterPlot [./reactives/plot.R#103]
     98: scatterPlot
     97: do.call
     96: reactive plotInput [./reactives/plot.R#192]
     85: plotInput
     78: isolate
     77: renderPlot [./observeEvents.R#23]
     69: output$plot
      2: shiny::runApp
      1: ggraptR::ggraptR
```

PS: Run on latest github install.

**Comment by grayskripko** [comment]
I have added many changes to that part of logic and now I can not reproduce that error. Please, try new unreleased version using devtools::install_github('grayskripko/raptR'). If the error will back, please, give me full steps description to reproduce it.
My current version changes column names automatically:
![image](https://cloud.githubusercontent.com/assets/10427026/18590060/af9c4b22-7c2d-11e6-8548-20948fb9a1c0.png)

![image](https://cloud.githubusercontent.com/assets/10427026/18590110/e2937ef6-7c2d-11e6-9743-f315b31d4f31.png)
