### ISSUE TITLE
exporting code 

### ISSUE THREAD

**Issue by Pakillo** [cargomoose/ggraptR#3]
Hi,

Thanks for the package. Looks really great!

I am wondering if it's possible to get/export the code used to produce a given plot (besides the plot itself). I can imagine it can be useful to, once you have a plot you like, be able to save the code needed to produce it (e.g. for reproducing it in the future).

I would be grateful if you can point out how to do that, or consider implementing that capability in the future.

Thanks again!

**Comment by cargomoose** [comment]
This is the next major feature on our list. We will get busy with this once we have put raptR on CRAN

**Comment by cargomoose** [comment]
And you're very welcome, please keep the feedback and suggestions coming !

**Comment by Pakillo** [comment]
Great. Looking forward to it. 
Cheers

**Comment by grayskripko** [comment]
I have sent such pull request. I hope that functionality will appear in a couple of days

**Comment by grayskripko** [comment]
done
