### ISSUE TITLE
infinite recursion error on opening app

### ISSUE THREAD

**Issue by Rmadillo** [cargomoose/ggraptR#4]
Getting error message of `Warning: Error in : evaluation nested too deeply: infinite recursion / options(expressions=)?` at opening of app. 

Running `options(expressions=5e5)` in console gives error message of `Error: C stack usage  19925872 is too close to the limit`. 

I don't know enough to know what to do here! :-)

**Comment by grayskripko** [comment]
How can we reproduce it? I did not meet that error
